### ISSUE TITLE
Removing entities from the World

### ISSUE THREAD

**Issue by UplinkPhobia** [HexDecimal/python-tcod-ecs#9]
Hello,

I was wondering if there is a way to delete/remove an entity from the world.
Typically, if I want to remove an obsolete entity, I would do a `entity.clear()` which would effectively make the entity "invisible" to queries, if I'm not mistaken; however, the world keeps a reference to the entity which prevents it from being deleted.

Is this intentional? Doesn't it create a memory leak where creating many entities lead to an increasing amount of references to objects that are not used anymore? Or did I miss something?

Thanks.

**Comment by HexDecimal** [comment]
> Doesn't it create a memory leak where creating many entities lead to an increasing amount of references to objects that are not used anymore? Or did I miss something?

What you're missing is that ***the information needed to query the entities is itself the strong reference the world has to that entity***. After `entity.clear()` is called then the only strong references left to that entity are either entity relations targeting that entity and any references that you've made outside of the world object.  All entities are also stored in a global weak dictionary which does not not keep them alive by itself.

`entity.clear()` not removing the entity as the target of other entities is something I'll likely fix.

**Comment by HexDecimal** [comment]
As a simpler explanation. If you invoke `entity = world.new_entity()` then the name `entity` becomes the only strong reference to that new Entity object. The only way to keep it alive is to assign a component to it, etc.

**Comment by UplinkPhobia** [comment]
I see... However, what I did to test (and might contain a subtlety that I did not notice) is

```python
>>> from tcod.ecs import World

>>> world = tcod.ecs.World()
>>> entity = world.new_entity(components=[object()])
>>> uid = entity.uid
>>> entity.clear()
>>> del entity

>>> world[uid]
Out[7]: <Entity(uid=object at 0x7F09E248A260)>
```

Since to my knowledge the UID doesn't contain a reference to the entity, and I removed other references to the entity, shouldn't it be removed and as such not possible to access from the world? Or is the UID referencing the entity in a way that I'm not aware of?

**Comment by HexDecimal** [comment]
> Since to my knowledge the UID doesn't contain a reference to the entity, and I removed other references to the entity, shouldn't it be removed and as such not possible to access from the world?

This is correct, you understand how UID's work and what you think should happen did happen. The entity was very likely deleted until you reused the UID to make a new entity with an equivalent UID. I can verify that entities don't leak.

The `world[uid]` syntax always does either of the following:

* Fetches the existing entity with that world/uid combo.
* Creates a new entity with that world/uid combo if it does not exist.

You'll never get a KeyError from this syntax. This is used for entity singletons, such as using `world[None]` as a place to store global components, or converting a hashable object to be used as a relation target.
```py
>>> world[None].components[str] = "Easy global components"

>>> world[None].relation_tag["Level"] = world[10]  # Allows queries by value
>>> world.Q.all_of(relations=[("Level", world[10])]).get_entities()  # Query by value
{<Entity(uid=None)>}
```

Note that the following two lines do the same thing:
```py
>>> entity = world.new_entity()
>>> entity = world[object()]
```

No matter what you do, fetching two entities using the same uid will always return an object with the same identity.
```py
>>> world[uid] is world[uid]
True
```
This last part is actually the important part and is the entire reason I made this silly setup.  If objects share the same identity than CPython can skip the `__eq__` test when checking if an object exists in a set, which this library does a lot of when doing queries.

**Comment by UplinkPhobia** [comment]
I see, that's where I lacked understanding of how things work. I did expect the world to either raise an exception, or return nothing, when asking for an UID that was not created through the typical `new_entity` function.

Thanks for the detailed explanation!
